version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.232.130'
      GITLAB_ROOT_PASSWORD: 'SuperSecurePassword123'
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    restart: always

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
