- name: Update and upgrade the system
  apt:
    update_cache: yes
    upgrade: dist
    force: yes 

- name: Install common dependencies
  apt:
    name:
      - curl
      - wget
      - vim
      - net-tools
      - ca-certificates
      - openssh-server
    state: present
